// =============================================================================
// PRAEFECTUS — Tabela COMPLETA de CFOP (Código Fiscal de Operações e Prestações)
// Fonte oficial: Receita Federal — Anexo CFOP/ECF 2022 (atualizado em 15/06/2023)
// https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/acoes-e-programas/facilitacao/anexo-ecf-cfop
//
// Total: 296 CFOPs (148 saídas oficiais ECF + 148 entradas espelhadas).
// Convenção do dígito inicial:
//   1xxx = Entrada — mesma UF        | 5xxx = Saída — mesma UF
//   2xxx = Entrada — outra UF        | 6xxx = Saída — outra UF
//   3xxx = Entrada do exterior       | 7xxx = Saída para o exterior
// =============================================================================

export type CFOPCompleto = {
  codigo: string;
  descricao: string;
  tipo: "entrada" | "saida";
  uf_destino: "mesma" | "outra" | "exterior";
  categoria: string;
};

export const CFOPS_COMPLETOS: CFOPCompleto[] = [
  { codigo: "1101", descricao: "Compra de produção do estabelecimento", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1102", descricao: "Compra de mercadoria adquirida ou recebida de terceiros", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1103", descricao: "Compra de produção do estabelecimento, efetuada fora do estabelecimento", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1104", descricao: "Compra de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1105", descricao: "Compra de produção do estabelecimento, que não deva por ele transitar", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1106", descricao: "Compra de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1109", descricao: "Compra de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1110", descricao: "Compra de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1111", descricao: "Compra de produção do estabelecimento remetida anteriormente em consignação industrial", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1112", descricao: "Compra de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1113", descricao: "Compra de produção do estabelecimento remetida anteriormente em consignação mercantil", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1114", descricao: "Compra de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1115", descricao: "Compra de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1116", descricao: "Compra de produção do estabelecimento originada de encomenda para entrega futura", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1117", descricao: "Compra de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1118", descricao: "Compra de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1119", descricao: "Compra de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1120", descricao: "Compra de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1122", descricao: "Compra de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente,sem transitar pelo estabelecimento do adquirente", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1123", descricao: "Compra de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1124", descricao: "Industrialização efetuada por outra empresa", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1125", descricao: "Industrialização efetuada por outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1129", descricao: "Compra de insumo importado e de mercadoria industrializada sob o amparo do Recof-Sped", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1132", descricao: "Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço de ato cooperativo", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1159", descricao: "Aquisição de produção do estabelecimento de ato cooperativo", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1160", descricao: "Aquisição de mercadoria adquirida ou recebida de terceiros de ato cooperativo", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1251", descricao: "Compra de energia elétrica para distribuição ou comercialização", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1252", descricao: "Compra de energia elétrica para estabelecimento industrial", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1253", descricao: "Compra de energia elétrica para estabelecimento comercial", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1254", descricao: "Compra de energia elétrica para estabelecimento prestador de serviço de transporte", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1255", descricao: "Compra de energia elétrica para estabelecimento prestador de serviço de comunicação", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1256", descricao: "Compra de energia elétrica para estabelecimento de produtor rural", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1257", descricao: "Compra de energia elétrica para consumo por demanda contratada", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1258", descricao: "Compra de energia elétrica a não contribuinte", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1301", descricao: "Aquisição de serviço de comunicação para execução de serviço da mesma natureza", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1302", descricao: "Aquisição de serviço de comunicação a estabelecimento industrial", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1303", descricao: "Aquisição de serviço de comunicação a estabelecimento comercial", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1304", descricao: "Aquisição de serviço de comunicação a estabelecimento de prestador de serviço de transporte", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1305", descricao: "Aquisição de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1306", descricao: "Aquisição de serviço de comunicação a estabelecimento de produtor rural", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1307", descricao: "Aquisição de serviço de comunicação a não contribuinte", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1351", descricao: "Aquisição de serviço de transporte para execução de serviço da mesma natureza", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1352", descricao: "Aquisição de serviço de transporte a estabelecimento industrial", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1353", descricao: "Aquisição de serviço de transporte a estabelecimento comercial", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1354", descricao: "Aquisição de serviço de transporte a estabelecimento de prestador de serviço de comunicação", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1355", descricao: "Aquisição de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1356", descricao: "Aquisição de serviço de transporte a estabelecimento de produtor rural", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1357", descricao: "Aquisição de serviço de transporte a não contribuinte", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1359", descricao: "Aquisição de serviço de transporte a contribuinte ou a não-contribuinte, quando a mercadoria transportada esteja dispensada de emissão de Nota Fiscal", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1360", descricao: "Aquisição de serviço de transporte a contribuinte-substituto em relação ao serviço de transporte (ACR)", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1401", descricao: "Compra de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1402", descricao: "Compra de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1403", descricao: "Compra de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1405", descricao: "Compra de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituído", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1456", descricao: "Saída referente a remuneração do produtor - Sistema de Integração e Parceria Rural", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1501", descricao: "Remessa de produção do estabelecimento, com fim específico de exportação", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1502", descricao: "Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1651", descricao: "Compra de combustível ou lubrificante de produção do estabelecimento destinados à industrialização subseqüente", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1652", descricao: "Compra de combustível ou lubrificante, de produção do estabelecimento, destinados à comercialização", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1653", descricao: "Compra de combustível ou lubrificante, de produção do estabelecimento, destinados a consumidor ou usuário final", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1654", descricao: "Compra de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à industrialização subseqüente", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1655", descricao: "Compra de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à comercialização", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1656", descricao: "Compra de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados a consumidor ou usuário final", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1667", descricao: "Compra de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra unidade da Federação", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1932", descricao: "Aquisição de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "1933", descricao: "Aquisição de serviço tributado pelo Imposto Sobre Serviços de Qualquer Natureza", tipo: "entrada", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2101", descricao: "Compra de produção do estabelecimento", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2102", descricao: "Compra de mercadoria adquirida ou recebida de terceiros", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2103", descricao: "Compra de produção do estabelecimento, efetuada fora do estabelecimento", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2104", descricao: "Compra de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2105", descricao: "Compra de produção do estabelecimento, que não deva por ele transitar", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2106", descricao: "Compra de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2107", descricao: "Compra de produção do estabelecimento, destinada a não contribuinte", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2108", descricao: "Compra de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2109", descricao: "Compra de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2110", descricao: "Compra de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2111", descricao: "Compra de produção do estabelecimento remetida anteriormente em consignação industrial", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2112", descricao: "Compra de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2113", descricao: "Compra de produção do estabelecimento remetida anteriormente em consignação mercantil", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2114", descricao: "Compra de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2115", descricao: "Compra de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2116", descricao: "Compra de produção do estabelecimento originada de encomenda para entrega futura", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2117", descricao: "Compra de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2118", descricao: "Compra de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2119", descricao: "Compra de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2120", descricao: "Compra de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2122", descricao: "Compra de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2123", descricao: "Compra de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2124", descricao: "Industrialização efetuada por outra empresa", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2125", descricao: "Industrialização efetuada por outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2129", descricao: "Compra de insumo importado e de mercadoria industrializada sob o amparo do Recof-Sped", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2132", descricao: "Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço ou fixação de preço de ato cooperativo", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2159", descricao: "Aquisição de produção do estabelecimento de ato cooperativo", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2160", descricao: "Aquisição de mercadoria adquirida ou recebida de terceiros de ato cooperativo", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2251", descricao: "Compra de energia elétrica para distribuição ou comercialização", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2252", descricao: "Compra de energia elétrica para estabelecimento industrial", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2253", descricao: "Compra de energia elétrica para estabelecimento comercial", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2254", descricao: "Compra de energia elétrica para estabelecimento prestador de serviço de transporte", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2255", descricao: "Compra de energia elétrica para estabelecimento prestador de serviço de comunicação", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2256", descricao: "Compra de energia elétrica para estabelecimento de produtor rural", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2257", descricao: "Compra de energia elétrica para consumo por demanda contratada", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2258", descricao: "Compra de energia elétrica a não contribuinte", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2301", descricao: "Aquisição de serviço de comunicação para execução de serviço da mesma natureza", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2302", descricao: "Aquisição de serviço de comunicação a estabelecimento industrial", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2303", descricao: "Aquisição de serviço de comunicação a estabelecimento comercial", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2304", descricao: "Aquisição de serviço de comunicação a estabelecimento de prestador de serviço de transporte", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2305", descricao: "Aquisição de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2306", descricao: "Aquisição de serviço de comunicação a estabelecimento de produtor rural", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2307", descricao: "Aquisição de serviço de comunicação a não contribuinte", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2351", descricao: "Aquisição de serviço de transporte para execução de serviço da mesma natureza", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2352", descricao: "Aquisição de serviço de transporte a estabelecimento industrial", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2353", descricao: "Aquisição de serviço de transporte a estabelecimento comercial", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2354", descricao: "Aquisição de serviço de transporte a estabelecimento de prestador de serviço de comunicação", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2355", descricao: "Aquisição de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2356", descricao: "Aquisição de serviço de transporte a estabelecimento de produtor rural", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2357", descricao: "Aquisição de serviço de transporte a não contribuinte", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2359", descricao: "Aquisição de serviço de transporte a contribuinte ou a não-contribuinte, quando a mercadoria transportada esteja dispensada de emissão de Nota Fiscal", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2360", descricao: "Aquisição de serviço de transporte a contribuinte substituto em relação ao serviço de transporte", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2401", descricao: "Compra de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2402", descricao: "Compra de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2403", descricao: "Compra de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2404", descricao: "Compra de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2456", descricao: "Saída referente a remuneração do produtor - Sistema de Integração e Parceria Rural", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2501", descricao: "Remessa de produção do estabelecimento, com fim específico de exportação", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2502", descricao: "Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2651", descricao: "Compra de combustível ou lubrificante, de produção do estabelecimento, destinados à industrialização subseqüente", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2652", descricao: "Compra de combustível ou lubrificante, de produção do estabelecimento, destinados à comercialização", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2653", descricao: "Compra de combustível ou lubrificante, de produção do estabelecimento, destinados a consumidor ou usuário final", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2654", descricao: "Compra de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à industrialização subseqüente", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2655", descricao: "Compra de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à comercialização", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2656", descricao: "Compra de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados a consumidor ou usuário final", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2667", descricao: "Compra de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra unidade da Federação diferente da que ocorrer o consumo", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2932", descricao: "Aquisição de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "2933", descricao: "Aquisição de serviço tributado pelo Imposto Sobre Serviços de Qualquer Natureza", tipo: "entrada", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "3101", descricao: "Compra de produção do estabelecimento", tipo: "entrada", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "3102", descricao: "Compra de mercadoria adquirida ou recebida de terceiros", tipo: "entrada", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "3105", descricao: "Compra de produção do estabelecimento, que não deva por ele transitar", tipo: "entrada", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "3106", descricao: "Compra de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar", tipo: "entrada", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "3127", descricao: "Compra de produção do estabelecimento sob o regime de ?drawback?", tipo: "entrada", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "3129", descricao: "Compra de produção do estabelecimento ao mercado externo de mercadoria industrializada sob o amparo do Recof-Sped", tipo: "entrada", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "3251", descricao: "Compra de energia elétrica para distribuição ou comercialização", tipo: "entrada", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "3301", descricao: "Aquisição de serviço de comunicação para execução de serviço da mesma natureza", tipo: "entrada", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "3358", descricao: "Aquisição de serviço de transporte", tipo: "entrada", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "3501", descricao: "Exportação de mercadorias recebidas com fim específico de exportação", tipo: "entrada", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "3504", descricao: "Exportação de mercadoria que foi objeto de formação de lote de exportação", tipo: "entrada", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "3651", descricao: "Compra de combustível ou lubrificante de produção do estabelecimento", tipo: "entrada", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "3654", descricao: "Compra de combustível ou lubrificante adquiridos ou recebidos de terceiros", tipo: "entrada", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "3667", descricao: "Compra de combustível ou lubrificante a consumidor ou usuário final", tipo: "entrada", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5101", descricao: "Venda de produção do estabelecimento", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5102", descricao: "Venda de mercadoria adquirida ou recebida de terceiros", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5103", descricao: "Venda de produção do estabelecimento, efetuada fora do estabelecimento", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5104", descricao: "Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5105", descricao: "Venda de produção do estabelecimento, que não deva por ele transitar", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5106", descricao: "Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5109", descricao: "Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5110", descricao: "Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5111", descricao: "Venda de produção do estabelecimento remetida anteriormente em consignação industrial", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5112", descricao: "Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5113", descricao: "Venda de produção do estabelecimento remetida anteriormente em consignação mercantil", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5114", descricao: "Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5115", descricao: "Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5116", descricao: "Venda de produção do estabelecimento originada de encomenda para entrega futura", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5117", descricao: "Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5118", descricao: "Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5119", descricao: "Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5120", descricao: "Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5122", descricao: "Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente,sem transitar pelo estabelecimento do adquirente", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5123", descricao: "Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5124", descricao: "Industrialização efetuada para outra empresa", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5125", descricao: "Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5129", descricao: "Venda de insumo importado e de mercadoria industrializada sob o amparo do Recof-Sped", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5132", descricao: "Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço de ato cooperativo", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5159", descricao: "Fornecimento de produção do estabelecimento de ato cooperativo", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5160", descricao: "Fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5251", descricao: "Venda de energia elétrica para distribuição ou comercialização", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5252", descricao: "Venda de energia elétrica para estabelecimento industrial", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5253", descricao: "Venda de energia elétrica para estabelecimento comercial", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5254", descricao: "Venda de energia elétrica para estabelecimento prestador de serviço de transporte", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5255", descricao: "Venda de energia elétrica para estabelecimento prestador de serviço de comunicação", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5256", descricao: "Venda de energia elétrica para estabelecimento de produtor rural", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5257", descricao: "Venda de energia elétrica para consumo por demanda contratada", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5258", descricao: "Venda de energia elétrica a não contribuinte", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5301", descricao: "Prestação de serviço de comunicação para execução de serviço da mesma natureza", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5302", descricao: "Prestação de serviço de comunicação a estabelecimento industrial", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5303", descricao: "Prestação de serviço de comunicação a estabelecimento comercial", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5304", descricao: "Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5305", descricao: "Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5306", descricao: "Prestação de serviço de comunicação a estabelecimento de produtor rural", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5307", descricao: "Prestação de serviço de comunicação a não contribuinte", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5351", descricao: "Prestação de serviço de transporte para execução de serviço da mesma natureza", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5352", descricao: "Prestação de serviço de transporte a estabelecimento industrial", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5353", descricao: "Prestação de serviço de transporte a estabelecimento comercial", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5354", descricao: "Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5355", descricao: "Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5356", descricao: "Prestação de serviço de transporte a estabelecimento de produtor rural", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5357", descricao: "Prestação de serviço de transporte a não contribuinte", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5359", descricao: "Prestação de serviço de transporte a contribuinte ou a não-contribuinte, quando a mercadoria transportada esteja dispensada de emissão de Nota Fiscal", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5360", descricao: "Prestação de serviço de transporte a contribuinte-substituto em relação ao serviço de transporte (ACR)", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5401", descricao: "Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5402", descricao: "Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5403", descricao: "Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5405", descricao: "Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituído", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5456", descricao: "Saída referente a remuneração do produtor - Sistema de Integração e Parceria Rural", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5501", descricao: "Remessa de produção do estabelecimento, com fim específico de exportação", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5502", descricao: "Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5651", descricao: "Venda de combustível ou lubrificante de produção do estabelecimento destinados à industrialização subseqüente", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5652", descricao: "Venda de combustível ou lubrificante, de produção do estabelecimento, destinados à comercialização", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5653", descricao: "Venda de combustível ou lubrificante, de produção do estabelecimento, destinados a consumidor ou usuário final", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5654", descricao: "Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à industrialização subseqüente", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5655", descricao: "Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à comercialização", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5656", descricao: "Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados a consumidor ou usuário final", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5667", descricao: "Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra unidade da Federação", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5932", descricao: "Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "5933", descricao: "Prestação de serviço tributado pelo Imposto Sobre Serviços de Qualquer Natureza", tipo: "saida", uf_destino: "mesma", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6101", descricao: "Venda de produção do estabelecimento", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6102", descricao: "Venda de mercadoria adquirida ou recebida de terceiros", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6103", descricao: "Venda de produção do estabelecimento, efetuada fora do estabelecimento", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6104", descricao: "Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6105", descricao: "Venda de produção do estabelecimento, que não deva por ele transitar", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6106", descricao: "Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6107", descricao: "Venda de produção do estabelecimento, destinada a não contribuinte", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6108", descricao: "Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6109", descricao: "Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6110", descricao: "Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6111", descricao: "Venda de produção do estabelecimento remetida anteriormente em consignação industrial", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6112", descricao: "Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6113", descricao: "Venda de produção do estabelecimento remetida anteriormente em consignação mercantil", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6114", descricao: "Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6115", descricao: "Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6116", descricao: "Venda de produção do estabelecimento originada de encomenda para entrega futura", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6117", descricao: "Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6118", descricao: "Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6119", descricao: "Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6120", descricao: "Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6122", descricao: "Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6123", descricao: "Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6124", descricao: "Industrialização efetuada para outra empresa", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6125", descricao: "Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6129", descricao: "Venda de insumo importado e de mercadoria industrializada sob o amparo do Recof-Sped", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6132", descricao: "Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço ou fixação de preço de ato cooperativo", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6159", descricao: "Fornecimento de produção do estabelecimento de ato cooperativo", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6160", descricao: "Fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6251", descricao: "Venda de energia elétrica para distribuição ou comercialização", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6252", descricao: "Venda de energia elétrica para estabelecimento industrial", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6253", descricao: "Venda de energia elétrica para estabelecimento comercial", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6254", descricao: "Venda de energia elétrica para estabelecimento prestador de serviço de transporte", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6255", descricao: "Venda de energia elétrica para estabelecimento prestador de serviço de comunicação", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6256", descricao: "Venda de energia elétrica para estabelecimento de produtor rural", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6257", descricao: "Venda de energia elétrica para consumo por demanda contratada", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6258", descricao: "Venda de energia elétrica a não contribuinte", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6301", descricao: "Prestação de serviço de comunicação para execução de serviço da mesma natureza", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6302", descricao: "Prestação de serviço de comunicação a estabelecimento industrial", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6303", descricao: "Prestação de serviço de comunicação a estabelecimento comercial", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6304", descricao: "Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6305", descricao: "Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6306", descricao: "Prestação de serviço de comunicação a estabelecimento de produtor rural", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6307", descricao: "Prestação de serviço de comunicação a não contribuinte", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6351", descricao: "Prestação de serviço de transporte para execução de serviço da mesma natureza", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6352", descricao: "Prestação de serviço de transporte a estabelecimento industrial", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6353", descricao: "Prestação de serviço de transporte a estabelecimento comercial", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6354", descricao: "Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6355", descricao: "Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6356", descricao: "Prestação de serviço de transporte a estabelecimento de produtor rural", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6357", descricao: "Prestação de serviço de transporte a não contribuinte", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6359", descricao: "Prestação de serviço de transporte a contribuinte ou a não-contribuinte, quando a mercadoria transportada esteja dispensada de emissão de Nota Fiscal", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6360", descricao: "Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6401", descricao: "Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6402", descricao: "Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6403", descricao: "Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6404", descricao: "Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6456", descricao: "Saída referente a remuneração do produtor - Sistema de Integração e Parceria Rural", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6501", descricao: "Remessa de produção do estabelecimento, com fim específico de exportação", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6502", descricao: "Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6651", descricao: "Venda de combustível ou lubrificante, de produção do estabelecimento, destinados à industrialização subseqüente", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6652", descricao: "Venda de combustível ou lubrificante, de produção do estabelecimento, destinados à comercialização", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6653", descricao: "Venda de combustível ou lubrificante, de produção do estabelecimento, destinados a consumidor ou usuário final", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6654", descricao: "Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à industrialização subseqüente", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6655", descricao: "Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à comercialização", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6656", descricao: "Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados a consumidor ou usuário final", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6667", descricao: "Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra unidade da Federação diferente da que ocorrer o consumo", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6932", descricao: "Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "6933", descricao: "Prestação de serviço tributado pelo Imposto Sobre Serviços de Qualquer Natureza", tipo: "saida", uf_destino: "outra", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "7101", descricao: "Venda de produção do estabelecimento", tipo: "saida", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "7102", descricao: "Venda de mercadoria adquirida ou recebida de terceiros", tipo: "saida", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "7105", descricao: "Venda de produção do estabelecimento, que não deva por ele transitar", tipo: "saida", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "7106", descricao: "Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar", tipo: "saida", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "7127", descricao: "Venda de produção do estabelecimento sob o regime de ?drawback?", tipo: "saida", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "7129", descricao: "Venda de produção do estabelecimento ao mercado externo de mercadoria industrializada sob o amparo do Recof-Sped", tipo: "saida", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "7251", descricao: "Venda de energia elétrica para distribuição ou comercialização", tipo: "saida", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "7301", descricao: "Prestação de serviço de comunicação para execução de serviço da mesma natureza", tipo: "saida", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "7358", descricao: "Prestação de serviço de transporte", tipo: "saida", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "7501", descricao: "Exportação de mercadorias recebidas com fim específico de exportação", tipo: "saida", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "7504", descricao: "Exportação de mercadoria que foi objeto de formação de lote de exportação", tipo: "saida", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "7651", descricao: "Venda de combustível ou lubrificante de produção do estabelecimento", tipo: "saida", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "7654", descricao: "Venda de combustível ou lubrificante adquiridos ou recebidos de terceiros", tipo: "saida", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
  { codigo: "7667", descricao: "Venda de combustível ou lubrificante a consumidor ou usuário final", tipo: "saida", uf_destino: "exterior", categoria: "VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS" },
];

/** Índice por código para busca O(1). */
export const CFOPS_INDEX: Record<string, CFOPCompleto> = Object.freeze(
  Object.fromEntries(CFOPS_COMPLETOS.map((c) => [c.codigo, c]))
);

/** Categorias únicas, em ordem alfabética — útil para filtros agrupados. */
export const CFOPS_CATEGORIAS: string[] = Array.from(
  new Set(CFOPS_COMPLETOS.map((c) => c.categoria))
).sort((a, b) => a.localeCompare(b, "pt-BR"));

/** Filtra CFOPs por tipo + destino. */
export function filtrarCFOPs(opts: {
  tipo?: "entrada" | "saida";
  uf_destino?: "mesma" | "outra" | "exterior";
  categoria?: string;
  termo?: string;
}): CFOPCompleto[] {
  const termo = opts.termo?.toLowerCase().trim();
  return CFOPS_COMPLETOS.filter((c) => {
    if (opts.tipo && c.tipo !== opts.tipo) return false;
    if (opts.uf_destino && c.uf_destino !== opts.uf_destino) return false;
    if (opts.categoria && c.categoria !== opts.categoria) return false;
    if (termo) {
      return c.codigo.includes(termo) || c.descricao.toLowerCase().includes(termo);
    }
    return true;
  });
}

/** Sugere CFOP de venda padrão baseado em UF emitente/destinatário e perfil do destinatário. */
export function sugerirCFOPVenda(
  ufEmitente: string,
  ufDestinatario: string,
  contribuinte = true
): string {
  if (!ufDestinatario) return "5102";
  if (ufEmitente === ufDestinatario) return "5102";          // Venda interna
  return contribuinte ? "6102" : "6108";                      // Interestadual contribuinte / consumidor final
}
