-- ═══════════════════════════════════════════════════════════════════════════
-- SUBSTITUÍDA — NÃO APLICAR. Ver 20260901000002.
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Esta migration nunca pôde ser aplicada: referenciava uma função
-- (`fn_alerta_legal_contrato`) e uma tabela (`contrato_auditoria`) que não
-- existem — foram deduzidas em vez de lidas do código real. Aplicá-la teria
-- criado uma função órfã que gatilho nenhum chama, e falhado no DELETE.
--
-- A correção verdadeira — a mesma regra de inclusão, na função que existe
-- (`recalcular_alertas_aditivos_contrato`, tabela `contrato_ia_auditoria`) —
-- está na 20260901000002_prorrogacao_fora_do_alerta_na_funcao_que_existe.sql.
--
-- O arquivo fica como registro do erro: objeto de banco se LÊ, não se deduz.
