// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://uwtyuwktxalnpgrcbbgk.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3dHl1d2t0eGFsbnBncmNiYmdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk5MTI5NjEsImV4cCI6MjA5NTQ4ODk2MX0.czjUoTkYoy0jxJcmaBGmiNposNrtcvL_wjUo-rMrqk8';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
